-- ACL Schema for Spring Security ACL
-- These tables store Access Control Lists for domain objects

-- Table for storing different domain object classes
CREATE TABLE IF NOT EXISTS acl_class (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    class VARCHAR(255) NOT NULL UNIQUE
);

-- Table for storing Security Identities (users and roles)
CREATE TABLE IF NOT EXISTS acl_sid (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    principal BOOLEAN NOT NULL,
    sid VARCHAR(100) NOT NULL UNIQUE
);

-- Table for storing individual domain object instances
CREATE TABLE IF NOT EXISTS acl_object_identity (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    object_id_class BIGINT NOT NULL,
    object_id_identity BIGINT NOT NULL,
    parent_object BIGINT,
    owner_sid BIGINT,
    entries_inheriting BOOLEAN NOT NULL,
    UNIQUE(object_id_class, object_id_identity),
    CONSTRAINT fk_acl_object_identity_parent FOREIGN KEY (parent_object) REFERENCES acl_object_identity(id),
    CONSTRAINT fk_acl_object_identity_class FOREIGN KEY (object_id_class) REFERENCES acl_class(id),
    CONSTRAINT fk_acl_object_identity_owner FOREIGN KEY (owner_sid) REFERENCES acl_sid(id)
);

-- Table for storing ACL entries (permissions)
CREATE TABLE IF NOT EXISTS acl_entry (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    acl_object_identity BIGINT NOT NULL,
    ace_order INTEGER NOT NULL,
    sid BIGINT NOT NULL,
    mask INTEGER NOT NULL,
    granting BOOLEAN NOT NULL,
    audit_success BOOLEAN NOT NULL,
    audit_failure BOOLEAN NOT NULL,
    UNIQUE(acl_object_identity, ace_order),
    CONSTRAINT fk_acl_entry_object FOREIGN KEY (acl_object_identity) REFERENCES acl_object_identity(id),
    CONSTRAINT fk_acl_entry_acl FOREIGN KEY (sid) REFERENCES acl_sid(id)
);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_acl_object_identity ON acl_object_identity(object_id_class, object_id_identity);
CREATE INDEX IF NOT EXISTS idx_acl_entry ON acl_entry(acl_object_identity);
